### PR TITLE
dropdown mixin

### PR DESCRIPTION
**Pull request by nazartokar**

### CODE REVIEW

**Review by jarrodek — CHANGES_REQUESTED** [review]
See description for this file:
https://github.com/advanced-rest-client/anypoint-styles/blob/master/dropdown-menu.html

Don't apply special mixin for the Anypoint dropdown since it should be applied in the master style file for the dropdown so you will only change it once (all anypoint dropdowns will inherit from the master style file).

**Comment by nazartokar** [comment]
@jarrodek I see this include: `<style include="anypoint-dropdown-menu-styles"></style>`

Does it mean we can have this style which will be applied to all dropdowns?

```
--anypoint-dropdown-menu-styles: {
@apply(--anypoint-dropdown-menu);
}
```

**Comment by jarrodek** [comment]
No, it doesn't work like that @nazartokar 

You have to include a style definition in an element and then add a class name to the dropdown:
```
<dom-module>
  <template>
    <style include="anypoint-dropdown-menu-styles"></style>
    <paper-dropdown-menu class="anypoint-dropdown-menu">
      ...
    </paper-dropdown-menu>
  </template>
</dom-module>
```

**Comment by nazartokar** [comment]
@jarrodek I see, so there's already a `.anypoint-dropdown-menu` class, I'll add styling to it.

**Review by jarrodek — APPROVED** [review]

**Pull request merged**
